version: '3'

services:
  web:
    build:
      context: ./TaskFlow
    container_name: site
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: TaskFlow.settings
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Timofey19
      POSTGRES_DB: taskflowdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: daphne TaskFlow.asgi:application  # Используем daphne для работы с ASGI

  db:
    image: postgres:latest
    container_name: DB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskflowdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Timofey19
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"

volumes:
  db_data: